FundsupWebApplication/Models/ViewModels/SearchDonateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FundsupWebApplication.Models.ViewModels
{
    public class SearchDonateViewModel
    {
        public string SearchText { get; set; }
        public long DonorKey { get; set; }
        public List<Entity.CauseEntity> Causes { get; set; }
    }
}

FundsupWebApplication/Controllers/DonorController.cs
using FundsupWebApplication.API;
using FundsupWebApplication.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FundsupWebApplication.Controllers
{
    //[Authorize]
    public class DonorController : Controller
    {
        // GET: Doner            ModelState.Clear();            ModelState.Clear();
        public ActionResult Profile(long donorKey)
        {
            var donor = new Models.DBContext.DonorClass().GetDonor(donorKey);
            if (donor == null)
                throw new ApplicationException("Donor Key cannot be null");
            
            return View(donor);
        }

        public ActionResult UploadProfilePicture(long donorKey)
        {
            Models.ViewModels.ContentViewModel model = new Models.ViewModels.ContentViewModel
            {
                DonorKey = donorKey,
            };
            return View();
        }

        [HttpPost]
        public ActionResult UploadProfilePicture(Models.ViewModels.ContentViewModel model)
        {
            HttpPostedFileBase file = Request.Files["ImageData"];

            if(ModelState.IsValid)
            { 
                //TODO add some more security around image add. 
                new Models.DBContext.DonorClass().UploadImageInDataBase(file, model);
                return RedirectToAction("Profile", new { donorKey = model.DonorKey });
            }

            return View(model);
        }

        #region EditDonor
        [HttpGet]
        public ActionResult EditDonor(long donorKey)
        {
            var model = new Models.DBContext.DonorClass().GetDonor(donorKey);
            if (model == null)
                throw new ApplicationException("Donor Key cannot be null");

            return View(model);
        }

        [HttpPost]
        public ActionResult EditDonor(DonorEntity model)
        {
            if(ModelState.IsValid)
            {
                new Models.DBContext.DonorClass().EditDonor(model);
                return RedirectToAction("Profile", new { donorKey = model.Key });
            }

            if (model == null)
                throw new ApplicationException("Donor Key cannot be null");

            return View(model);
        }
        #endregion

        #region EditCause
        [HttpGet]
        public ActionResult EditCause(long? causeKey, long donorKey)
        {
            var model = new Models.ViewModels.CauseViewModel
            { 
                DonorKey = donorKey,
                Cause = causeKey.HasValue && causeKey.Value > 0 ? new Models.DBContext.CauseClass().GetCause(causeKey.Value) : new CauseEntity(),
                Milestones = new List<MilestoneEntity>(),
                NewMilestone = new MilestoneEntity
                {
                     Amount = 0,
                     StartDate = DateTime.Now,
                     EndDate = DateTime.Now,
                     Name = string.Empty,
                },
            };

            if (causeKey.HasValue && causeKey.Value > 0)
            {
                model.NewMilestone.CauseKey = causeKey.Value;
                model.Milestones = new Models.DBContext.MilestoneClass().GetMilestonesPerCause(causeKey.Value);
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult EditCause(Models.ViewModels.CauseViewModel model)
        {
            if (model.Milestones == null)
                model.Milestones = new List<MilestoneEntity>();

            if (ModelState.IsValid)
            {

                //edit cause details
                var cause = new Models.DBContext.CauseClass().EditDonorCause(model.Cause, model.DonorKey);

                if (model.NewMilestone.CauseKey == 0)
                    model.NewMilestone.CauseKey = cause.Key;

                //add new milestone
                new Models.DBContext.MilestoneClass().EditMilestone(model.NewMilestone);

                //edit existing milestones
                
                foreach(var milestone in model.Milestones)
                {
                    new Models.DBContext.MilestoneClass().EditMilestone(milestone);
                }

                //return RedirectToAction("Profile", new { donorKey = model.DonorKey });
            }

            ModelState.Clear();
            model.NewMilestone = new MilestoneEntity
            {
                EndDate = DateTime.Now,
                StartDate = DateTime.Now,
                Amount = 0,
            };

            if (model == null)
                throw new ApplicationException("Cause Key cannot be null");

            model.Milestones = new Models.DBContext.MilestoneClass().GetMilestonesPerCause(model.Cause.Key);
            model.NewMilestone = new MilestoneEntity
            {
                Amount = 0,
                StartDate = DateTime.Now,
                EndDate = DateTime.Now,
                Name = string.Empty,
            };
            return View(model);
        }
        #endregion

        #region SearchDonate
        [HttpGet]
        public ActionResult SearchDonate(long donorKey)
        {
            Models.ViewModels.SearchDonateViewModel model = new Models.ViewModels.SearchDonateViewModel
            {
                DonorKey = donorKey,
                Causes = new List<CauseEntity>(),
                SearchText = string.Empty,
            };
            
            return View(model);
        }

        [HttpPost]
        public ActionResult SearchDonate(Models.ViewModels.SearchDonateViewModel model)
        {

            if (String.IsNullOrEmpty(model.SearchText))
                model.Causes = new List<CauseEntity>();
            else
                model.Causes = new Models.DBContext.CauseClass().GetFilteredCauses(model.SearchText);

            return View(model);
        }

        #endregion

        #region EditDonation
        [HttpGet]
        public ActionResult EditDonation(long? causeKey, long donorKey)
        {
            var model = new Models.ViewModels.DonateViewModel
            {
                DonorKey = donorKey,
                Cause = causeKey.HasValue && causeKey.Value > 0 ? new Models.DBContext.CauseClass().GetCause(causeKey.Value) : new CauseEntity(),
                Milestones = new List<MilestoneEntity>(),
            };

            if (causeKey.HasValue && causeKey.Value > 0)
            {
                model.Milestones = new Models.DBContext.MilestoneClass().GetMilestonesPerCause(causeKey.Value);
                model.Milestones.ForEach(s => s.Amount = 0);
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult EditDonation(Models.ViewModels.DonateViewModel model)
        {
            if (model.Milestones == null)
                model.Milestones = new List<MilestoneEntity>();

            if (ModelState.IsValid)
            {
               long transactionKey = new Models.DBContext.DonorClass().Donate(model.Milestones, model.Cause.Amount, model.DonorKey, model.Cause.Key);
                if (transactionKey != 0)
                    return RedirectToAction("BankPaymentProcess", new { donorKey = model.DonorKey, causeKey = model.Cause.Key, transactionKey = transactionKey });
                else
                    ModelState.AddModelError("transactionKey is 0", "Transaction was not processes. Please make sure the donation amounts are greater than 0.");
            }

            if (model == null)
                throw new ApplicationException("Cause Key cannot be null");

            model.Milestones = new Models.DBContext.MilestoneClass().GetMilestonesPerCause(model.Cause.Key);

            return View(model);
        }
        #endregion

        #region BankPaymentProcess
        [HttpGet]
        public ActionResult BankPaymentProcess(long donorKey, long causeKey, long transactionKey)
        {
            Models.ViewModels.PaymentViewModel model = new Models.ViewModels.PaymentViewModel
            {
                DonorKey = donorKey,
                Cause = new Models.DBContext.DonationClass().GetDonationAmount(transactionKey),
                TransactionKey = transactionKey,
                CreditCardTypes = new API.EcentricWebAPI().GetCreditCardTypes() ,
                ExpiryMonths = new API.EcentricWebAPI().GetCreditCardMonths(),
                ExpiryYears = new API.EcentricWebAPI().GetCreditCardYears(),
            };
            return View(model);
        }

        [HttpGet]
        public ActionResult PublishProfile(long causeKey, long donorKey)
        {
            new Models.DBContext.CauseClass().PublishProfile(causeKey);
            return RedirectToAction("Profile", new { causeKey = causeKey, donorKey = donorKey });
        }


        [HttpPost]
        public ActionResult BankPaymentProcess(Models.ViewModels.PaymentViewModel model)
        {
            ModelState.Remove("Cause.ShortDescription");
            ModelState.Remove("Cause.Description");

            if (ModelState.IsValid)
            {
                var onceOffRequest = new PayFastRequest(Sessions.SiteSettings.SandboxPassphrase);

                // Merchant Details
                onceOffRequest.merchant_id = Sessions.SiteSettings.SandboxMerchantID;
                onceOffRequest.merchant_key = Sessions.SiteSettings.SandboxMerchantKey;
                onceOffRequest.return_url = Url.Action("ReturnUrl", new { } );
                onceOffRequest.cancel_url = Url.Action("CancelUrl", new { });
                onceOffRequest.notify_url = Url.Action("NotifyUrl", new { });

                // Buyer Details
                onceOffRequest.email_address = "sbtu01@payfast.co.za";

                // Transaction Details
                onceOffRequest.m_payment_id = "8d00bf49-e979-4004-228c-08d452b86380";
                onceOffRequest.amount = 130;
                onceOffRequest.item_name = "Once off option";

FundsupWebApplication/Views/Donor/BankPaymentProcess.cshtml
@model FundsupWebApplication.Models.ViewModels.PaymentViewModel

@{
    ViewBag.Title = "Payment Processing";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new {  });
    <div class="form-horizontal">
        <h4>Process Donation</h4>
        @Html.HiddenFor(model => model.Cause.Key)
        @Html.HiddenFor(model => model.Cause.Description)
        @Html.HiddenFor(model => model.Cause.ShortDescription)
        @Html.HiddenFor(model => model.Cause.Name)
        @Html.HiddenFor(model => model.Cause.Amount)
        @Html.HiddenFor(model => model.DonorKey)
        @Html.HiddenFor(model => model.TransactionKey)

        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-md-12">You are about to donate R<span>@Model.Cause.Amount</span> towards the @Model.Cause.Name Venture</div>
        </div>

        <div class="row mt-1">
            <div class="col-md-2"><b>@Html.Label("Card Type", htmlAttributes: new { @class = "control-label" })</b></div>
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.CreditCardType, Model.CreditCardTypes, "", new { @class = "form-control", style = "max-width:100% !important" })
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-md-2"><b>@Html.Label("Name on Card", htmlAttributes: new { @class = "control-label" })</b></div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.CreditcardHolderName, new { htmlAttributes = new { @class = "form-control", style = "max-width:100% !important", placeholder = "Name on credit card" } })
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-md-2"><b>@Html.Label("Card Number", htmlAttributes: new { @class = "control-label" })</b></div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.CreditCardNumber, new { htmlAttributes = new { @class = "form-control", style = "max-width:100% !important", placeholder = "Card Number" } })
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-md-2"><b>@Html.Label("Expiry Date", htmlAttributes: new { @class = "control-label" })</b></div>
            <div class="col-md-2">
                @Html.DropDownListFor(model => model.ExpiryMonth, Model.ExpiryMonths, "", new { @class = "form-control", style = "max-width:100% !important" })
            </div>
            <div class="col-md-1 ml-0 mr-0 pl-0 pr-0 text-center" style="line-height:40px;"><b>/</b></div>
            <div class="col-md-2">
                @Html.DropDownListFor(model => model.ExpiryYear, Model.ExpiryYears, "", new { @class = "form-control", style = "max-width:100% !important" })
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-md-2"><b>@Html.Label("CCV", htmlAttributes: new { @class = "control-label" })</b></div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.CCV, new { htmlAttributes = new { @class = "form-control", style = "max-width:100% !important", placeholder = "CCV" } })
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-md-12 text-center">
                <input type="submit" value="Proceed with donation" class="btn btn-success btn-block" />
            </div>
        </div>
        <br />
    </div>
}

FundsupWebApplication/Views/Donor/CancelUrl.cshtml
@{
    ViewBag.Title = "CancelUrl";
}

<h2>CancelUrl</h2>

FundsupWebApplication/Views/Donor/EditCause.cshtml
@model FundsupWebApplication.Models.ViewModels.CauseViewModel
@{
    ViewBag.Title = "Edit Venture";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.DonorKey)

    if (Model.Cause.Key > 0)
    {
        @Html.HiddenFor(model => model.NewMilestone.CauseKey)
    }

    if (Model.Cause.Key > 0)
    {
        @Html.HiddenFor(model => model.Cause.Key)
    }
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row mb-5">
        <div class="col-md-12">
            <a class="font-weight-bold" href="@Url.Action("Profile", "Donor", new { donorKey = Model.DonorKey })" title="return to Profile"><i class="fa fa-2x fa-arrow-circle-left"></i></a>
        </div>
        <b>@Html.Label("Venture", htmlAttributes: new { @class = "control-label col-md-12 mt-1 mb-0" })</b>
        <div class="col-md-12">
            @Html.EditorFor(model => model.Cause.Name, new { htmlAttributes = new { @class = "form-control", style = "max-width:100% !important", placeholder = "Venture name" } })
            @Html.ValidationMessageFor(model => model.Cause.Name, "", new { @class = "text-danger" })
        </div>

        <b>@Html.Label("Short Description of Venture", htmlAttributes: new { @class = "control-label col-md-12 mt-1 mb-0" })</b>
        <div class="col-md-12">
            @Html.EditorFor(model => model.Cause.ShortDescription, new { htmlAttributes = new { @class = "form-control", style = "max-width:100% !important", placeholder = "Give a short description of the venture no longer than 50 characters." } })
            @Html.ValidationMessageFor(model => model.Cause.ShortDescription, "", new { @class = "text-danger" })
        </div>

        <b>@Html.Label("Tell us more about the Venture", htmlAttributes: new { @class = "control-label col-md-12 mt-1 mb-0" })</b>
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Cause.Description, new { @class = "form-control", @cols = 12, @rows = 6, style = "max-width:100% !important", placeholder = "Give a detailed description of the venture to attract donors..." })
            @Html.ValidationMessageFor(model => model.Cause.Description, "", new { @class = "text-danger" })
        </div>

        <b>@Html.Label("Funding required", htmlAttributes: new { @class = "control-label col-md-12 mt-1 mb-0" })</b>
        <div class="col-md-4">
            @Html.EditorFor(model => model.Cause.Amount, new { htmlAttributes = new { @class = "form-control", placeholder = "Total funding required" } })
            @Html.ValidationMessageFor(model => model.Cause.Amount, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-8">
            @{
                double totalMilestonesAmount = 0;
                double differenceAmount = 0;
                if (Model.Milestones != null && Model.Milestones.Count > 0)
                {
                    totalMilestonesAmount = Model.Milestones.Sum(x => x.Amount);
                    differenceAmount = (double)Model.Cause.Amount - totalMilestonesAmount;
                }
            }

            <i>Milestones total to <b>R @totalMilestonesAmount</b>. There is a difference of <b>R @differenceAmount</b> compared to the total funding required. </i>
        </div>

        <div class="col-md-12 mt-3">
            <div class="row">
                <div class="col-md-12"><b>Milestones (add at least 1 Milestones)</b></div>
            </div>
        </div>
        <div class="col-md-12">
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Name</th>
                        <th>Start</th>
                        <th>End</th>
                        <th>Amount</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="">
                        <td>
                            @Html.EditorFor(model => model.NewMilestone.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Add new milestone" } })
                        </td>
                        <td>
                            @Html.EditorFor(model => model.NewMilestone.StartDate, new { htmlAttributes = new { @class = "form-control datepicker", placeholder = "Start date" } })
                        </td>
                        <td>
                            @Html.EditorFor(model => model.NewMilestone.EndDate, new { htmlAttributes = new { @class = "form-control datepicker", placeholder = "End date" } })
                        </td>
                        <td>
                            @Html.EditorFor(model => model.NewMilestone.Amount, new { htmlAttributes = new { @class = "form-control", placeholder = "Amount", onclick = "this.Select()" } })
                        </td>
                        <td><button type="submit" class="btn btn-block btn-success" value="Add Milestone" title="Add Milestone"><i class="fa fa-plus"></i></button></td>
                    </tr>


                    @if (Model.Milestones != null && Model.Milestones.Count > 0)
                    {
                        for (int i = 0; i < Model.Milestones.Count(); i++)
                        {
                            @Html.HiddenFor(model => Model.Milestones[i].CauseKey)
                            @Html.HiddenFor(model => Model.Milestones[i].Key)
                            <tr class="alert-warning">
                                <td>@Html.EditorFor(model => Model.Milestones[i].Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Milestone" } })</td>
                                <td>@Html.EditorFor(model => Model.Milestones[i].StartDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Start Date" } })</td>
                                <td>@Html.EditorFor(model => Model.Milestones[i].EndDate, new { htmlAttributes = new { @class = "form-control", placeholder = "End Date" } })</td>
                                <td>@Html.EditorFor(model => Model.Milestones[i].Amount, new { htmlAttributes = new { @class = "form-control", placeholder = "Amount" } })</td>
                                <td></td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5" class="danger">
                                No Milestones have been captured.
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <button type="submit" class="btn btn-block btn-success mb-2" value="Save Venture" title="Save Venture">Save Venture</button>
                </div>
                <div class="col-md-6">
                    @if (Model.Cause.IsPublished)
                    {
                        <button type="button" class="btn btn-block btn-danger publishStatus" value="Unpublish" title="Unpublish" data-toggle="modal" data-target="#publishModal">Unpublish</button>
                    }
                    else
                    {
                        <button type="button" class="btn btn-block btn-warning publishStatus" value="Publish" title="Publish" data-toggle="modal" data-target="#publishModal">Publish</button>
                    }
                </div>
            </div>
        </div>
    </div>


}

<!-- Modal -->
<div class="modal fade" id="publishModal" tabindex="-1" role="dialog" aria-labelledby="publishModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="publishModalLabel">
                    @if (Model.Cause.IsPublished)
                    {
                        <span>Unpublish</span>
                    }
                    else
                    {
                        <span>Publish</span>
                    }

                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @if (Model.Cause.IsPublished)
                {
                    <span>Are you sure you want to unpublish this venture? This means donors will no longer be able to view it.</span>
                }
                else
                {
                    <span>Are you sure you want to publish this venture?</span>
                }
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-primary">Yes</button>*@
                @Html.ActionLink("Yes","PublishProfile",new { causeKey = Model.Cause.Key, donorKey = Model.DonorKey }, new { @class="btn btn-primary" })
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FundsupWebApplication/Views/Donor/EditDonation.cshtml
@model FundsupWebApplication.Models.ViewModels.DonateViewModel
@{
    /**/

    ViewBag.Title = "EditCause";
}

<div class="row">
    <div class="col-md-1">
        <a class="font-weight-bold" href="@Url.Action("SearchDonate","Donor", new { donorKey = Model.DonorKey })" title="return to Profile"><i class="fa fa-2x fa-arrow-circle-left"></i></a>
    </div>
    <div class="col-md-11">
        <h2>Donate towards @Html.DisplayFor(model => model.Cause.Name, new { htmlAttributes = new { @class = "form-control" } })</h2>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.DonorKey)
    if (Model.Cause.Key > 0)
    {
        @Html.HiddenFor(model => model.Cause.Key)
    }
    @Html.HiddenFor(model => model.Cause.Description)
    @Html.HiddenFor(model => model.Cause.ShortDescription)
    @Html.HiddenFor(model => model.Cause.Name)

    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Cause.Description, new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Cause.ShortDescription, new { @class = "form-control" })
        </div>

    </div>
    <div class="row mt-5">
        <div class="col-md-4" style="line-height:45px;">Donate towards the whole venture:</div>
        <div class="col-md-8">  @Html.EditorFor(model => model.Cause.Amount, new { htmlAttributes = new { @class = "form-control", placeholder = "Amount" } })</div>
    </div>
    <div class="row mt-2">
        <div class="col-md-12">Donate towards the specified milestones</div>
        <div class="col-md-12">
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Name</th>
                        <th>start Date</th>
                        <th>End Date</th>
                        <th>Amount</th>
                        @*<th></th>*@
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Milestones != null && Model.Milestones.Count > 0)
                    {
                        for (int i = 0; i < Model.Milestones.Count(); i++)
                        {
                            @Html.HiddenFor(model => Model.Milestones[i].CauseKey)
                            @Html.HiddenFor(model => Model.Milestones[i].Key)
                            <tr>
                                <td>
                                    @Html.EditorFor(model => Model.Milestones[i].Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Milestone", @readonly = true } })
                                    @Html.HiddenFor(model => Model.Milestones[i].Name)
                                </td>
                                <td>
                                    @Html.EditorFor(model => Model.Milestones[i].StartDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Start Date", @readonly = true } })
                                    @Html.HiddenFor(model => Model.Milestones[i].StartDate)
                                </td>
                                <td>
                                    @Html.EditorFor(model => Model.Milestones[i].EndDate, new { htmlAttributes = new { @class = "form-control", placeholder = "End Date", @readonly = true } })
                                    @Html.HiddenFor(model => Model.Milestones[i].EndDate)
                                </td>
                                <td>@Html.EditorFor(model => Model.Milestones[i].Amount, new { htmlAttributes = new { @class = "form-control", placeholder = "Amount" } })</td>
                                @*<td>@Html.ActionLink("Edit", "EditCause", "Donor", new { causeKey = milestone.Key }, new { })</td>*@
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5" class="text-warning">
                                No Milestones have been captured.
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 ">
            <input type="submit" value="Donate" class="btn btn-default btn-block btn-success pull-right" />
        </div>
    </div>
    <br />

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FundsupWebApplication/Views/Donor/SearchDonate.cshtml
@model FundsupWebApplication.Models.ViewModels.SearchDonateViewModel
@{   
  ViewBag.Title = "SearchDonate";
}

<div class="row view-background">
    @using (@Html.BeginForm("SearchDonate", "Donor", FormMethod.Post, new { @style = "width:100%" }))
    {
        @Html.HiddenFor(model => model.DonorKey)
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12"><a class="font-weight-bold" href="@Url.Action("Profile","Donor", new { donorKey = Model.DonorKey })" title="return to Profile"><i class="fa fa-2x fa-arrow-circle-left"></i></a> &nbsp;&nbsp; Search for ventures by making use of keywords.</div>
            </div>
            <div class="row">
                <div class="col-md-8">  @Html.EditorFor(model => model.SearchText, new { htmlAttributes = new { @class = "form-control", @style="max-width:100% !important", placeholder="Search for a venture" } }) </div>
                <div class="col-md-4">  <button type="submit" class="btn btn-success btn-block"> Search </button> </div>
            </div>
        </div>
        <div class="col-md-12 mt-3">
            @if (Model.Causes != null)
            {
                <table class="table table-bordered">
                    <thead class="thead-light">
                        <tr>
                            @*<th>Key</th>*@
                            <th scope="col">Name</th>
                            <th scope="col">Description</th>
                            <th>Donate</th>
                        </tr>
                    </thead>
                    <tbody>

                        @if (Model.Causes.Count != 0)
                        {
                            foreach (var cause in Model.Causes)
                            {

                                <tr class="causes-created">
                                    @*<td>@cause.Key</td>*@
                                    <td>@cause.Name</td>
                                    <td>@cause.ShortDescription</td>
                                    <td>
                                        <a href="@Url.Action("EditDonation", "Donor", new { causeKey = cause.Key, donorKey = Model.DonorKey })"><i class="fa fa-2x fa-hand-o-right"></i></a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr class="causes-created">
                                @*<td>@cause.Key</td>*@
                                <td colspan="3" class="text-danger">No ventures registered on platform.</td>
                            </tr>
                        }

                    </tbody>
                </table>
            }
        </div>
    }

</div>

FundsupWebApplication/Views/Donor/UploadProfilePicture.cshtml
@model FundsupWebApplication.Models.ViewModels.ContentViewModel

@{
    ViewBag.Title = "Upload Profile Picture";
}

<div class="row">
    <div class="col-md-12">
        <h4>Select and Upload your profile pic...</h4>
    </div>
</div>

@using (Html.BeginForm("UploadProfilePicture", "Donor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.DonorKey)

    <div class="row">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-12">
            <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
        </div>

        <div class="col-md-12">
            <input type="submit" value="Create" class="btn btn-success btn-block" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>